NV-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update nv bills --realtime"
  enabled: true
  environment: scrapers
  triggers:
#    - cron: 0 */6 * * ?
    - cron: 0 2,8,14,20 * * ?
  timeout_minutes: 360
  next_tasks:
    - NV-text

NV-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update nv"
  enabled: true
  environment: scrapers
