NY-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update ny bills --realtime"
  enabled: true
  environment: scrapers
  memory: 1024
  triggers:
    # - cron: 0 1,19 * * ?
    - cron: 0 */12 * * ?
  timeout_minutes: 600  # regularly 7 hours, 10 to be safe
  next_tasks:
    - NY-text

NY-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update ny"
  enabled: true
  environment: scrapers
