TN-scrape:
  image: openstates/scrapers
  entrypoint: "poetry run os-update tn bills --realtime"
  enabled: false
  memory: 1024
  environment: scrapers
  triggers:
    - cron: 23 */6 * * ?
#    - cron: 0 5 * * ?
  timeout_minutes: 360
  next_tasks:
    - TN-text

TN-text:
  image: openstates/core
  entrypoint: "poetry run os-text-extract update tn"
  enabled: false
  environment: scrapers
